server:
  port: 8881
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bd71:3306/leyou?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: "#@!L191010l"
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
#    # 每隔5秒发送一次心跳
#    lease-renewal-interval-in-seconds: 5
#    # 10秒不发送就过期
#    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}:${server.port}